name: Build Check

on:
  push:
    branches:
      - CICD

  pull_request:
    branches:
      - CICD

jobs:

  build-check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: |
            backend/yarn.lock
            frontend/yarn.lock

      # Backend

      - name: Install backend dependencies
        working-directory: backend
        run: yarn install --frozen-lockfile

      - name: Build backend
        working-directory: backend
        run: yarn build

      # Frontend

      - name: Install frontend dependencies
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Build frontend
        working-directory: frontend
        run: yarn build