name: First CI Pipeline

on:
  push:
    branches:
      - CICD

  pull_request:
    branches:
      - CICD

jobs:
  explore-runner:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Show GitHub context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
          echo "Actor: $GITHUB_ACTOR"
          echo "Commit: $GITHUB_SHA"

      - name: Show current directory
        run: |
          pwd
          ls -lah

      - name: Show Docker version
        run: |
          docker --version
          docker compose version
