name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:

  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn install --frozen-lockfile

      - run: yarn build

  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn install --frozen-lockfile

      - run: yarn build

  docker-build-backend:
    needs: backend-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build backend image
        run: |
          docker build \
            -t todolist-backend:${{ github.sha }} \
            ./backend